### PR TITLE
Comment annotated feedback

### PR DESCRIPTION
**Pull request by Stephen-ONeil**
I'm going to commit my feedback as comments in the source of my fork, feel free to ask any clarifying questions in this PR (either as comments on this PR thread or code review comments directly on portions of my feedback comments).

### CODE REVIEW

**Comment by Stephen-ONeil** [comment]
I'll be pushing up some more as I find the time. Will try to keep them shorter than this first comment block, it was a bit of a rant. Going to focus a lot more on code than on design, but I did also click around on the GitHub pages site and found it pretty good!

**Comment by GarvinH** [comment]
All feedback has been implemented so far.
Thanks Stephen!

**Comment by Stephen-ONeil** [comment]
Two notes:
  1) I recommend doing work in branches and always opening a PR before merging in. Even in a project that only you're working on, it is a good habit to get in to. For any non-trivial branches, when you don't have colleagues, I find it useful to delay merging it a day so you can give it a self-review with fresh eyes the next day. Either way, most git work flows strongly discourage commits directly to master
  2) just a reminder that the things I'm choosing to comment on aren't necessarily things that need to be "fixed", they're things I think would make for good learning opportunities. Likewise, I'm not pointing out every single thing that I'd have done differently. While you're waiting on me to have time to write more comments, I recommend you do more reading on any concepts I've mentioned and then try applying the concepts through self-review of your code (e.g. single source of truth, DRY, etc.; doesn't have to be on the wikipedia links I gave, tons of more compelling blog posts on this stuff out there).

**Comment by Stephen-ONeil** [comment]
I'll try and get another comment or two in soon!

**Comment by GarvinH** [comment]
Thanks for the tips! I've attempted to DRY a section of my code out and made a PR as a test attempt.
If it looks good, I'll continue doing so. In the meantime, I'll continue to read a little more into what you've recommended.

**Comment by Stephen-ONeil** [comment]
This last batch throws a lot out there all at once, especially about accessibility considerations. I recommend reading through and digesting the comments from each commit one at a time and in order. Definitely concepts in there that I'm leaving up to you to google for more information on, just let me know if you want help finding good resources for any of them!

**Comment by GarvinH** [comment]
I suppose I'll ask about aria. Any links you recommend reading about? I did some research into it but nothing related to its history. On a side note, longdesc seems to be deprecated? In addition, I believe the usage was to link to webpages with more detail? I'm not too clear about how it works so I'd thought I'd ask.

**Comment by Stephen-ONeil** [comment]
Oh, huh! You're totally right, I had `longdesc` all wrong. Well, good thing I also never thought it was worth using! I don't like designing around images that need more than a couple words of explanation anyway.

**Comment by Stephen-ONeil** [comment]
I don't know a whole lot of the history of ARIA, but here's some context that will probably help:

Most of the standards that make up the internet, from the perspective of an internet browser are developed by a group called the World Wide Web Consortium (W3C). That includes everything from HTML to WebAssembly. The core administrative body of the W3C is relatively small I think, the members that sit in the committees are representatives and individuals from a long list of third parties.

**Important note:** the site w3schools.com that shows up at the top of a lot of CSS/HTML google searches has nothing to do with the standards body, and is a subpar resource to boot. The actual W#C website is w3.com. The best resource for web technology resources by far is the [MDN web docs](https://developer.mozilla.org/).

The standards that make up the internet from a communications perspective are governed by a separate group, the Internet Engineering Task Force (IETF). Talking stuff like TCP/IP. I think they have some role in certain W3C specs too? Not totally sure, but would guess they at least share a lot of members.

The third important group is Ecma (formerly the European Computer Manufacturers Association, but they changed their name to just Ecma when they became more of a global body). They control a number of specifications, but the only relevant one to us is EcmaScript (the specification for JavaScript). You'll see "es" used as a short hand in a lot of place in JavaScript technologies (eslint, ESM, etc.).

Then you have browser maintainers. They have to implement all of these specifications (well, sometimes they share or fork eachother's rendering or JS engines). They often choose to race ahead of the actual specifications, both in adding features they want to see added to spec and in deprecating existing features they want to kill faster. This is generally bad for everyone, because it just creates more cross-browser issues and more websites that only work in specific browsers. It also gives browsers with more market share, like Chrome, a ton of extra power over the standards committees.

... okay. Now to actually answer the question. ARIA attributes come from WAI-ARIA (Web Accessibility Initiative - Accessible Rich Internet Applications), one of the W3C standards. Sort of a meta standard that tries to wrangle a11y in to the other standards/combination of standards that make up the web. Aside from creating its own attributes for html, like `aria-hidden`, it also specifies how the semantics of HTML should be interpreted for screen readers.

W3C also publishes the Web Content Accessibility Guidelines (WCAG). This can be treated like something of a handbook for assessing and implementing a11y on a website. It lays out multiple levels (A, AA, AAA) of a11y that a website can achieve; those levels are generally used as targets by automated a11y testing tools/a11y assessment experts/developers. Since it's a guideline rather than a specification, I think it's the most worth reading for the average developer, if not in full.

**Pull request closed without merging**
